// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MotoPremija_WebAPI.SlojPodataka.EFCore.Kontekst;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MotoPremija_WebAPI.SlojPodataka.Migrations
{
    [DbContext(typeof(KontekstBazeAplikacije))]
    partial class KontekstBazeAplikacijeModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MotoPremija_WebAPI.SlojPodataka.Modeli.Korisnik", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Adresa")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("adresa");

                    b.Property<string>("BrVozackeDozvole")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasColumnName("brvozackedozvole");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("ime");

                    b.Property<string>("Imejl")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("imejl");

                    b.Property<string>("JMBG")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)")
                        .HasColumnName("jmbg");

                    b.Property<string>("LozinkaHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("lozinkahash");

                    b.Property<string>("LozinkaSalt")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("lozinkasalt");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("prezime");

                    b.Property<long>("Telefon")
                        .HasColumnType("bigint")
                        .HasColumnName("telefon");

                    b.Property<string>("Uloga")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("uloga");

                    b.HasKey("Id");

                    b.ToTable("korisnik");
                });

            modelBuilder.Entity("MotoPremija_WebAPI.SlojPodataka.Modeli.Motocikl", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BrSaobracajneDozvole")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("brsaobracajnedozvole");

                    b.Property<string>("BrendModel")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("brendmodel");

                    b.Property<int>("GodinaProizvodnje")
                        .HasColumnType("integer")
                        .HasColumnName("godinaproizvodnje");

                    b.Property<Guid>("KorisnikId")
                        .HasColumnType("uuid")
                        .HasColumnName("korisnikid");

                    b.Property<string>("PrimarnaUpotreba")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("primarnaupotreba");

                    b.HasKey("Id");

                    b.HasIndex("KorisnikId");

                    b.ToTable("motocikl");
                });

            modelBuilder.Entity("MotoPremija_WebAPI.SlojPodataka.Modeli.Osiguranje", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BrPolise")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasColumnName("brpolise");

                    b.Property<double>("GodisnjaPremija")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("godisnjapremija");

                    b.Property<Guid>("MotociklId")
                        .HasColumnType("uuid")
                        .HasColumnName("motociklid");

                    b.Property<Guid>("TipOsiguranjaId")
                        .HasColumnType("uuid")
                        .HasColumnName("tiposiguranjaid");

                    b.HasKey("Id");

                    b.HasIndex("MotociklId");

                    b.HasIndex("TipOsiguranjaId");

                    b.ToTable("osiguranje");
                });

            modelBuilder.Entity("MotoPremija_WebAPI.SlojPodataka.Modeli.TipOsiguranja", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<double>("BaznaPremija")
                        .HasColumnType("double precision")
                        .HasColumnName("baznapremija");

                    b.Property<string>("NazivOsiguranja")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("nazivosiguranja");

                    b.HasKey("Id");

                    b.ToTable("tiposiguranja");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            BaznaPremija = 100.0,
                            NazivOsiguranja = "Osiguranje od odgovornosti"
                        },
                        new
                        {
                            Id = new Guid("22222211-2222-2222-2222-222222222222"),
                            BaznaPremija = 250.0,
                            NazivOsiguranja = "Kasko osiguranje"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            BaznaPremija = 150.0,
                            NazivOsiguranja = "Osiguranje od štete usled sudara"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            BaznaPremija = 200.0,
                            NazivOsiguranja = "Pokriće neosiguranog vozila"
                        });
                });

            modelBuilder.Entity("MotoPremija_WebAPI.SlojPodataka.Modeli.Motocikl", b =>
                {
                    b.HasOne("MotoPremija_WebAPI.SlojPodataka.Modeli.Korisnik", null)
                        .WithOne()
                        .HasForeignKey("MotoPremija_WebAPI.SlojPodataka.Modeli.Motocikl", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MotoPremija_WebAPI.SlojPodataka.Modeli.Korisnik", "Korisnik")
                        .WithMany()
                        .HasForeignKey("KorisnikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Korisnik");
                });

            modelBuilder.Entity("MotoPremija_WebAPI.SlojPodataka.Modeli.Osiguranje", b =>
                {
                    b.HasOne("MotoPremija_WebAPI.SlojPodataka.Modeli.Motocikl", null)
                        .WithMany()
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MotoPremija_WebAPI.SlojPodataka.Modeli.TipOsiguranja", null)
                        .WithMany()
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MotoPremija_WebAPI.SlojPodataka.Modeli.Motocikl", "Motocikl")
                        .WithMany()
                        .HasForeignKey("MotociklId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MotoPremija_WebAPI.SlojPodataka.Modeli.TipOsiguranja", "TipOsiguranja")
                        .WithMany()
                        .HasForeignKey("TipOsiguranjaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Motocikl");

                    b.Navigation("TipOsiguranja");
                });
#pragma warning restore 612, 618
        }
    }
}
